CREATE DATABASE DB_MOBLY_TEAMS;

USE DB_MOBLY_TEAMS;

CREATE TABLE TEAM(
ID					INT				AUTO_INCREMENT		PRIMARY KEY,
TEAM_NAME			VARCHAR(40)		NOT NULL,
SHELL_COLOR			VARCHAR(40)		NOT NULL,
DATE_FOUNDATION		DATE			NOT NULL,
CREATED_AT 			TIMESTAMP 		NOT NULL DEFAULT NOW(),
UPDATED_AT 			TIMESTAMP 		NOT NULL DEFAULT NOW() ON UPDATE NOW()
);

CREATE TABLE PLAYER(
ID					INT				AUTO_INCREMENT		PRIMARY KEY,
PLAYER_NAME			VARCHAR(40)		NOT NULL,
LAST_NAME			VARCHAR(40)		NOT NULL,
ID_TEAM				INT				NOT NULL,
SHIRT_NUMBER		INT				NOT NULL,
CREATED_AT 			TIMESTAMP 		NOT NULL DEFAULT NOW(),
UPDATED_AT 			TIMESTAMP 		NOT NULL DEFAULT NOW() ON UPDATE NOW(),
FOREIGN KEY (ID_TEAM) REFERENCES TEAM(ID)
);